### ISSUE TITLE
Monthly means are not being computed for December

### ISSUE THREAD

**Issue by gustavo-marques** [NCAR/MOM6#37]
When the model is run for one year at a time (i.e., for each job submission), the monthly mean file does not include the month of December.

**Comment by alperaltuntas** [comment]
I applied a temporary fix for this issue to correct the timing of (daily, monthly, etc.) mean outputs. To apply the fix, simply change your local FMS copy with a clone of the following FMS fork:

https://github.com/alperaltuntas/FMS

Note: the fix assumes all runs start and end at 00:00.

### The summary of the issue:
The issue occurs due to the **one coupling interval lag** for the ocean component in CESM. 

  - For example, if the ocean coupling interval is 30 minutes, MOM6 will start at 1/1/1, 00:**30**:00. The way FMS calculates the date at which the outputs are first written to a file is by adding the output frequency, say, 1 month, to the initial time. This means that the sampling of first monthly means will end at 1/2/1, 00:**30**:00. The subsequent outputting intervals are similarly computed: ```next_output_time = output_frequency + last_output_time```, meaning that the last monthly outputs will not be written since the time at which they are supposed to be written is 30 minutes after the time at which the run finishes.

### A temporary fix:

The following FMS fork includes a temporary fix in the ```fix_monthly_means``` branch where the end date of the first output interval gets moved to an earlier time, i.e., midnight. The change in the date is equal to one ocean coupling interval.This means, for monthly means, for example, the first output set covers a time span of 1 month - 1 ocn_coupling_interval. This also, automatically, corrects the subsequent outputting intervals.
https://github.com/alperaltuntas/FMS

The following are two 3-month runs. The first case, without the fix, misses the last month (march), whereas the second case has all three months saved in the monthly mean files.
```
/glade/scratch/altuntas/mom.e20.CMOM.T62_t061.monthly_mean_noFix.001
/glade/scratch/altuntas/mom.e20.CMOM.T62_t061.monthly_mean_fix.001
```

### TODO:
Touch base with GFDL to come up with a permanent solution.
